export const SELECT_LOCATION = 'SELECT_LOCATION';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const CHOSEN_SYMPTOMS = 'CHOSEN_SYMPTOMS';
export const FETCH_SYMPTOMS = 'FETCH_SYMPTOMS';
export const SAVE_FILE = 'SAVE_FILE';
export const PAGE_COUNTER = 'PAGE_COUNTER';
export const CHECK_HISTORY = 'CHECK_HISTORY';
